### ISSUE TITLE
[4.3] Subscription endpoint

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#127] opened 2019-08-14 14:36 UTC
Check the points:

1. User can subscribe for
1.1. initiative
1.2. geo area
1.3. tag + gea area
2. User can unsubscribe for particular choice.

**Comment by Asteur** [comment] 2020-04-08 09:35
Added. Test it

**Comment by rizomaa** [comment] 2020-04-16 20:25
@Asteur 
1/ Could you provide set of endpoints for testing here?
2/ Or did you use any online environment for developing them?
Please describe several steps for tester.

**Comment by Asteur** [comment] 2020-04-18 10:02
1. It is one endpoint /api/subscription, just send POST or DELETE with additional DATA in request parameters
```
curl -d '{"email":"aa@sd.com", "type":"I", "last_date": "1565122640", "subs_params":{"id":"123"}}' -H "Content-Type: application/json" -X POST http://localhost:3001/api/subscription

    curl -d '{"hashId":"fe24b489f8862f8ba21f17539271c2f16a7062cd"}' -H "Content-Type: application/json" -X DELETE http://localhost:3001/api/subscription
```

2. 'Developing' or 'testing'? I used `curl`, the tester can use it or install `httpie`, or use `postman` for testing APIs.

It will be better for the tester to set up this API according to steps in https://github.com/diglabby/mapa-subscription he can ping me in slack if he will need any help.

**Comment by ArtyomKr** [comment] 2020-04-30 06:52
So it works but need some testing?

**Comment by rizomaa** [comment] 2020-05-02 08:30
@ArtyomKr 
Sure.

1. It should be installed
2. Configured.
3. And tested all methods on the endpoint (marked by @Asteur here https://github.com/diglabby/mapa/issues/127#issuecomment-615835321)

**Comment by ArtyomKr** [comment] 2020-06-19 16:07
@rizomaa Okay, I tested provided requests (`POST` and `DELETE`) with postman and it works, but I encountered some oddities and I'm not sure if those are bugs or features.

1. You can add entries with the same email and type. If you run mailer, those emails will receive only 1 letter even if they are included in different entries, so it's still works correctly.

![image](https://user-images.githubusercontent.com/53486579/85152921-40ad7180-b25e-11ea-843d-e39fb39c3454.png)

2. Time of creation for entries is wrong, it's -2 hours. It's Greenwich timezone and maybe it's working as intended.

![Безыменны](https://user-images.githubusercontent.com/53486579/85151934-0a232700-b25d-11ea-861c-18b89b8f564a.png)

**Comment by rizomaa** [comment] 2020-06-22 13:17
@ArtyomKr about the second point don't worry, we can add in subscription module +3 hours and it will be correct in our case. But I think it is another task. If you feel it can play on proper work, please create a new issue.

About the first point. It is not clear for me what you mean here. 
You can discus the point in detail with @Asteur (he is a developer of subscription module). If it is bottle neck for task progress give we to know we can make call an solve it.

**Comment by ArtyomKr** [comment] 2020-06-22 13:33
@rizomaa 

> @ArtyomKr about the second point don't worry, we can add in subscription module +3 hours and it will be correct in our case. But I think it is another task. If you feel it can play on proper work, please create a new issue.

Yes, I understand, I only pointed at this just in case if it was unintended.

> About the first point. It is not clear for me what you mean here.
> You can discus the point in detail with @Asteur (he is a developer of subscription module). If it is bottle neck for task progress give we to know we can make call an solve it.

I meant that one email with one type of subscription can be in table multiple times. But after our discussion (https://github.com/diglabby/mapa/issues/128#issuecomment-645950478), I understood that this's how our subscription model should work. So it's okay.

**Comment by ArtyomKr** [comment] 2020-06-24 14:45
@rizomaa Can we close this issue or is there something else that I need to do?

**Comment by rizomaa** [comment] 2020-06-25 06:52
@ArtyomKr Please check one more time the points:

1. User can subscribe for
1.1. initiative
1.2. geo area
1.3. tag + gea area
2. User can unsubscribe for particular choice.

If the list - ok you can close. Does it make sense?

**Comment by ArtyomKr** [comment] 2020-06-25 08:21
@rizomaa All types of subscription are working and user can unsubscribe from their entries.  Than I will close this issue.

**Closed by ArtyomKr** 2020-06-25 08:21 UTC
Labels: 10 backend, hackathon, subscriptions

**Comment by rizomaa** [comment] 2020-06-28 06:29
@ArtyomKr я пакуль зармяшчу на праглядзе картку, на тыжни пагляджу яшчэ раз усё уважлива и тады зачыню. дзякуй за працу)
